version: '2'
services:
  db:
    image: mysql:5.7.33
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./.data/db:/var/lib/mysql
    ports:
      - 3306:3306
  web: &app
    image: kylebrothers/mywiki:latest
    build: .
    ports:
      - 8080:80
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    # uncomment the 'volumes' section to enable a shared volume with docker-compose
    volumes:
      - ./.data/web:/data:rw
      - ./CustomSettings.php:/conf/CustomSettings.php
      - ./images:/var/www/html/images:rw
      # do not uncomment this when starting a new instance from scratch as
      # init script won't be able to move this file
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
      #- ./CustomHooks.php:/var/www/html/CustomHooks.php
      # FIXME this is a custom change on Parsoid PHP implementation since mw 1.35.
      # the Parsoid domain is not configurable. so we needed to disable the check as we are using "localhost" in Restbase redirection
      - ./ParsoidHandler_custom_1_35.php:/var/www/html/vendor/wikimedia/parsoid/extension/src/Rest/Handler/ParsoidHandler.php
    environment:
      - MEDIAWIKI_SITE_SERVER=http://localhost:8080
      - MEDIAWIKI_SITE_NAME=BrothersBrothers
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_PASSWORD=password
      - MEDIAWIKI_UPGRADE_KEY=upgradekey
      # uncomment 'MEDIAWIKI_ENABLE_SSL' to enable SSL support
      # - MEDIAWIKI_ENABLE_SSL=true
      - MEDIAWIKI_EXTENSIONS=Arrays,Bootstrap,DataTransfer,HeaderTabs,HTMLets,ImageMap,Maps,PageForms,PageSchemas,ParserFunctions,Scribunto,SearchTool,SearchWikipedia,SemanticCite,SemanticCompoundQueries,SemanticExtraSpecialProperties,SemanticInterlanguageLinks,SemanticMediaWiki,SemanticMetaTags,SemanticResultFormats,SemanticScribunto,Validator,XSL
      - MEDIAWIKI_ALLOW_SITE_CSS_ON_RESTRICTED_PAGES=true
      - PARSOID_DOMAIN=localhost
      # RESTBASE_URL=http://nodeservices:7231
      # FIXME skip domain checking in Parsoid. used in our own ParsoidHandler_custom_xxxx.php.
      # in our Apache conf file, we are redirecting requests to restbase with domain "localhost",
      # but the Parsoid domain is not configurable.  hence disable the check.
      - PARSOID_SKIP_DOAMIN_CHECK=true
      # - AUTO_CREATED_USER_REDIRECT=UBC_Wiki:Welcome
      - MEDIAWIKI_MAIN_CACHE=redis
      - MEDIAWIKI_REDIS_HOST=redis
      - MEDIAWIKI_REDIS_PORT=6379
      #- MEDIAWIKI_REDIS_PASSWORD=
      - MEDIAWIKI_REDIS_PERSISTENT=true
      #- MEDIAWIKI_MAIN_CACHE=CACHE_NONE
      #- MEDIAWIKI_MEMCACHED_SERVERS=["memcached:11211"]
      # uncomment to specify the wgUploadPath
      # - MEDIAWIKI_UPLOAD_PATH=
      #- GOOGLE_ANALYTICS_ID=UA-XXXXXXX-XX
      # GoogleAnalyticsMetrics: https://www.mediawiki.org/wiki/Extension:GoogleAnalyticsMetrics
      #- GOOGLE_ANALYTICS_METRICS_ALLOWED
      #- GOOGLE_ANALYTICS_METRICS_PATH
      #- GOOGLE_ANALYTICS_METRICS_VIEWID
      - DEBUG=true
      # - CALIPER_HOST=https://caliper.imsglobal.org/caliper/PUT_TEST_BEARER_TOKEN_HERE/message
      # - CALIPER_API_KEY=PUT_TEST_BEARER_TOKEN_HERE
      # - CALIPER_BASE_URL=http://localhost:8888/test_url/
      # - CALIPER_LDAP_ACTOR_HOMEPAGE=http://media_wiki_ldap_homepage
  job_runner:
    <<: *app
    command: php /var/www/html/maintenance/runJobs.php --wait
    ports:
      - 8081:80

# use combined image for now
#  parsoid:
#    image: ubcctlt/parsoid
#    environment:
#      - MEDIAWIKI_API_URL=http://web/w/api.php
#      - MEDIAWIKI_DOMAIN=localhost
#      - MEDIAWIKI_PREFIX=localhost
#  restbase:
#    image: ubcctlt/restbase
#    environment:
#      - MEDIAWIKI_API_URL=http://web/w/api.php
#      - PARSOID_DOMAIN=localhost
#      - PARSOID_URL=http://parsoid:8000
  nodeservices:
    image: ubcctlt/mediawiki-node-services
    ports:
      - 7231:7231
    environment:
      - MEDIAWIKI_API_URL=http://web/api.php
      - MEDIAWIKI_REST_URL=http://web/rest.php
      - LOG_LEVEL=debug
    volumes:
      - ./.data/services:/data
#  memcached:
#    image: memcached:1.5-alpine
  redis:
    image: redis:6.0-alpine
